language: ruby
cache: ccache
sudo: required
dist: trusty
os:
  - linux

rvm:
  - 2.3.3

addons:
  ssh_known_hosts: staging.paddlepaddle.org

install:
  - bundle install

script:
  - |
    export DEPLOY_DOCS_SH=https://raw.githubusercontent.com/PaddlePaddle/PaddlePaddle.org/develop/scripts/deploy/deploy_docs.sh
    export BLOG_DIR=`pwd`
    cd ..
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "develop"  ||  "$TRAVIS_BRANCH" =~ ^v[[:digit:]]+\.[[:digit:]]+(\.[[:digit:]]+)?(-\S*)?$ ]]; then curl $DEPLOY_DOCS_SH | bash -s $CONTENT_DEC_PASSWD $TRAVIS_BRANCH $BLOG_DIR; else echo "not develop branch, no deploy"; fi;

notifications:
  email:
    on_success: change
    on_failure: always
